# Site settings
title: JANZ TALES
email: mdayubjanz@gmail.com
description: >- 
  Janz Tales की बेहतरीन कहानियाँ, आर्टिकल्स और ताज़ा अपडेट्स।
baseurl: "" 
url: "" 

# Build settings
# (यहाँ से minima थीम को हमेशा के लिए जड़ से उड़ा दिया गया है)

# Social links
github_username: JanzEducation
